[tool.ruff]
target-version = "py310"
line-length = 88
select = ["E", "F", "I", "U", "N"]
ignore = ["E501"]

[tool.pytest.ini_options]
pythonpath = ["."]

[tool.mypy]
python_version = "3.10"
warn_redundant_casts = true
disallow_untyped_calls = true
disallow_untyped_defs = true
no_implicit_optional = true

[[tool.mypy.overrides]]
module = "pytest.*"
ignore_missing_imports = true
